// Code generated by microgen 1.0.5. DO NOT EDIT.

package transporthttp

import (
	transport "github.com/SurajKadam7/session-service/sessions_svc/transport"
	httpkit "github.com/go-kit/kit/transport/http"
	"net/url"
)

func NewHTTPClient(u *url.URL, opts ...httpkit.ClientOption) transport.EndpointsSet {
	return transport.EndpointsSet{
		AddEndpoint: httpkit.NewClient(
			"POST", u,
			_Encode_Add_Request,
			_Decode_Add_Response,
			opts...,
		).Endpoint(),
		RemoveEndpoint: httpkit.NewClient(
			"POST", u,
			_Encode_Remove_Request,
			_Decode_Remove_Response,
			opts...,
		).Endpoint(),
		SendGroupMsgEndpoint: httpkit.NewClient(
			"POST", u,
			_Encode_SendGroupMsg_Request,
			_Decode_SendGroupMsg_Response,
			opts...,
		).Endpoint(),
		SendMsgEndpoint: httpkit.NewClient(
			"POST", u,
			_Encode_SendMsg_Request,
			_Decode_SendMsg_Response,
			opts...,
		).Endpoint(),
	}
}
