// Code generated by microgen 1.0.5. DO NOT EDIT.

// Please, do not change functions names!
package transporthttp

import (
	"bytes"
	"context"
	"encoding/json"
	transport "github.com/SurajKadam7/session-service/sessions_svc/transport"
	"io"
	"net/http"
	"path"
)

func CommonHTTPRequestEncoder(_ context.Context, r *http.Request, request interface{}) error {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(request); err != nil {
		return err
	}
	r.Body = io.NopCloser(&buf)
	return nil
}

func CommonHTTPResponseEncoder(_ context.Context, w http.ResponseWriter, response interface{}) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	return json.NewEncoder(w).Encode(response)
}

func _Decode_Add_Request(_ context.Context, r *http.Request) (interface{}, error) {
	var req transport.AddRequest
	err := json.NewDecoder(r.Body).Decode(&req)
	return &req, err
}

func _Decode_SendMsg_Request(_ context.Context, r *http.Request) (interface{}, error) {
	var req transport.SendMsgRequest
	err := json.NewDecoder(r.Body).Decode(&req)
	return &req, err
}

func _Decode_SendGroupMsg_Request(_ context.Context, r *http.Request) (interface{}, error) {
	var req transport.SendGroupMsgRequest
	err := json.NewDecoder(r.Body).Decode(&req)
	return &req, err
}

func _Decode_Remove_Request(_ context.Context, r *http.Request) (interface{}, error) {
	var req transport.RemoveRequest
	err := json.NewDecoder(r.Body).Decode(&req)
	return &req, err
}

func _Decode_Add_Response(_ context.Context, r *http.Response) (interface{}, error) {
	var resp transport.AddResponse
	err := json.NewDecoder(r.Body).Decode(&resp)
	return &resp, err
}

func _Decode_SendMsg_Response(_ context.Context, r *http.Response) (interface{}, error) {
	var resp transport.SendMsgResponse
	err := json.NewDecoder(r.Body).Decode(&resp)
	return &resp, err
}

func _Decode_SendGroupMsg_Response(_ context.Context, r *http.Response) (interface{}, error) {
	var resp transport.SendGroupMsgResponse
	err := json.NewDecoder(r.Body).Decode(&resp)
	return &resp, err
}

func _Decode_Remove_Response(_ context.Context, r *http.Response) (interface{}, error) {
	var resp transport.RemoveResponse
	err := json.NewDecoder(r.Body).Decode(&resp)
	return &resp, err
}

func _Encode_Add_Request(ctx context.Context, r *http.Request, request interface{}) error {
	r.URL.Path = path.Join(r.URL.Path, "add")
	return CommonHTTPRequestEncoder(ctx, r, request)
}

func _Encode_SendMsg_Request(ctx context.Context, r *http.Request, request interface{}) error {
	r.URL.Path = path.Join(r.URL.Path, "send-msg")
	return CommonHTTPRequestEncoder(ctx, r, request)
}

func _Encode_SendGroupMsg_Request(ctx context.Context, r *http.Request, request interface{}) error {
	r.URL.Path = path.Join(r.URL.Path, "send-group-msg")
	return CommonHTTPRequestEncoder(ctx, r, request)
}

func _Encode_Remove_Request(ctx context.Context, r *http.Request, request interface{}) error {
	r.URL.Path = path.Join(r.URL.Path, "remove")
	return CommonHTTPRequestEncoder(ctx, r, request)
}

func _Encode_Add_Response(ctx context.Context, w http.ResponseWriter, response interface{}) error {
	return CommonHTTPResponseEncoder(ctx, w, response)
}

func _Encode_SendMsg_Response(ctx context.Context, w http.ResponseWriter, response interface{}) error {
	return CommonHTTPResponseEncoder(ctx, w, response)
}

func _Encode_SendGroupMsg_Response(ctx context.Context, w http.ResponseWriter, response interface{}) error {
	return CommonHTTPResponseEncoder(ctx, w, response)
}

func _Encode_Remove_Response(ctx context.Context, w http.ResponseWriter, response interface{}) error {
	return CommonHTTPResponseEncoder(ctx, w, response)
}
