// Code generated by microgen 1.0.5. DO NOT EDIT.

package transporthttp

import (
	transport "github.com/SurajKadam7/session-service/sessions_svc/transport"
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	http1 "net/http"
)

func NewHTTPHandler(endpoints *transport.EndpointsSet, opts ...http.ServerOption) http1.Handler {
	mux := mux.NewRouter()
	mux.Methods("POST").Path("/add/").Handler(
		http.NewServer(
			endpoints.AddEndpoint,
			_Decode_Add_Request,
			_Encode_Add_Response,
			opts...))
	mux.Methods("POST").Path("/sendmsg/").Handler(
		http.NewServer(
			endpoints.SendMsgEndpoint,
			_Decode_SendMsg_Request,
			_Encode_SendMsg_Response,
			opts...))
	mux.Methods("POST").Path("/sendgroup/").Handler(
		http.NewServer(
			endpoints.SendGroupMsgEndpoint,
			_Decode_SendGroupMsg_Request,
			_Encode_SendGroupMsg_Response,
			opts...))
	mux.Methods("POST").Path("/remove/").Handler(
		http.NewServer(
			endpoints.RemoveEndpoint,
			_Decode_Remove_Request,
			_Encode_Remove_Response,
			opts...))
	return mux
}
