// Code generated by microgen 1.0.5. DO NOT EDIT.

package service

import service "github.com/SurajKadam7/session-service/sessions_svc"

// Service middleware (closure).
type Middleware func(service.Service) service.Service
