// Code generated by microgen 1.0.5. DO NOT EDIT.

package transport

import model "github.com/SurajKadam7/session-service/model"

type (
	AddRequest struct {
		SessionInfo model.SessionInfo `json:"session_info"`
	}
	AddResponse struct {
		Res model.SessionInfo `json:"res"`
	}

	SendMsgRequest struct {
		UserId  int           `json:"user_id"`
		Message model.Message `json:"message"`
	}
	SendMsgResponse struct {
		Status bool `json:"status"`
	}

	SendGroupMsgRequest struct {
		UserId  int           `json:"user_id"`
		GroupId int           `json:"group_id"`
		Message model.Message `json:"message"`
	}
	SendGroupMsgResponse struct {
		Status bool `json:"status"`
	}

	RemoveRequest struct {
		UserId int `json:"user_id"`
	}
	RemoveResponse struct {
		Res model.SessionInfo `json:"res"`
	}
)
